db:
  host: "127.0.0.1"
  port: 27017
  user: 
  pass: 
  db: "db_name" 
  debug: false

app:
  host: "0.0.0.0"
  port: 9001
  debug: true
  secret: 
  mail_account: 
  mail_pass: 

filehandler:
  root_path: './filecache'