db:
  host: 
  port: 
  user: 
  pass: 
  db:  
  debug: true
  timeout: 20000
  multi_threaded: false

app:
  host: "0.0.0.0"
  port: 9001
  prefix: ""
  debug: true
  secret: 
  mail_account: 
  mail_pass: 

filehandler:
  root_path: './filecache'